//
// Copyright 2011 GREE, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/**
 * @file GreeNotification.h
 * GreeNotification class
 */

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "GreeNotificationTypes.h"

/**
 * @brief The GreeNotification interface is the data model for a notification in the Gree Platform SDK.
 *
 * A GreeNotification is used to convey information from the platform directly to the user. 
 * GreeNotification objects are generated by platform APIs or iOS remote/local notifications and 
 * displayed by being added to a GreeNotificationQueue.
 */
@interface GreeNotification : NSObject

/**
 * @brief The notification message.
 */
@property (nonatomic, copy, readonly) NSString* message;
/**
 * @brief Controls how the notificaiton is displayed.
 */
@property (readonly) GreeNotificationViewDisplayType displayType;
/**
 * @brief The GreeNotification will display for this duration.
 * @see GreeNotificationInfiniteDuration
 */
@property (readonly) NSTimeInterval duration;

/**
 * @brief Initializes a GreeNotification.
 * @param message Notification message.
 * @param icon Notification icon image.
 * @param displayType Notification display type.
 * @param duration Notification duration.
 * @note Designated initializer
 */
- (id)initWithMessage:(NSString*)message 
  displayType:(GreeNotificationViewDisplayType)displayType
  duration:(NSTimeInterval)duration;

@end
